### ISSUE TITLE
Freeze with Fedora 35 and Java 18(build 11)

### ISSUE THREAD

**Issue by jamie-marchant** [JVoiceXML/FreeTTS#3]
I seem to have freezing after upgrading to Fedora 35 and Java 18, is this project still active.

**Comment by schnelle** [comment]
Sorry, to only check after that long time. Could you detail this issue?

**Comment by jamie-marchant** [comment]
Oh right this was a bug with Java on Fedora Core 35. FC 35 is no longer supported and the issue is fixed in 37. 

It was the incorrect opinion of someone on-line that the bug was with my program or the library I was using and not with Java itself. 

Since the issue has been fixed, I'll close this ticket.
